### ISSUE TITLE
How to deal with the increasing size of the global Gaussian point cloud?

### ISSUE THREAD

**Issue by fankeyu123** [wangys16/FreeSplat#1]

**Comment by wangys16** [comment]
Sorry for the late reply. Since we follow the previous generalizable 3DGS in unprojecting pixel-wise gaussians, the number of gaussians can potentially become large when given long sequence inputs. Therefore, our proposed PTF module can effectively remove redundant gaussians especially when input views have large overlaps, which can significantly improve the rendering FPS.
